version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "exbotanical"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore: "
      include: "scope"
    labels:
      - "npm dependencies"
      - "monorepo"

  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "exbotanical"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore(api): "
      include: "scope"
    labels:
      - "npm dependencies"
      - "api"

  - package-ecosystem: "npm"
    directory: "/packages/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "exbotanical"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore(client): "
      include: "scope"
    labels:
      - "npm dependencies"
      - "client"

  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "exbotanical"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore(common): "
      include: "scope"
    labels:
      - "npm dependencies"
      - "packages/common"
