name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:

  check:
    uses: /.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: check:ci

  test:
    uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: test

  # cy-test:
  #   uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
  #   with:
  #     script_name: test:cy
